### ISSUE TITLE
Don't compile libopenal & libtremor in VS2015.

### ISSUE THREAD

**Issue by Commondor** [AprilAndFriends/xal#2]
Don't compile libopenal & libtremor in VS2015. 

Error	MSB8006	The Platform for project 'libopenal.vcxproj' is invalid.  Platform='Android'. This error may also appear if some other project is trying to follow a project-to-project reference to this project, this project has been unloaded or is not included in the solution, and the referencing project does not build using the same or an equivalent Platform.

Error	MSB8006	The Platform for project 'libtremor.vcxproj' is invalid.  Platform='Android'. This error may also appear if some other project is trying to follow a project-to-project reference to this project, this project has been unloaded or is not included in the solution, and the referencing project does not build using the same or an equivalent Platform.

**Comment by borisblizzard** [comment]
Not a bug. These two projects are intended for Android using hl-android MSBuild scripts for Visual Studio. The scripts are located in hltypes/msvc/util/hl-android-v*. Of course Java, the Android SDK and the Android NDK are required for this to work.

If you are not compiling for Android, you can safely ignore this. We do plan to switch to Android Studio completely somewhere in the near future.
